-- Step 1: The Audit (Verification)
-- READ-ONLY
--
-- GENERATED from 049-duplicate-cleanup/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT 
    b.bib# AS [Bib Number],
    b.tagord AS [Target TagOrd],
    b.text AS [Current Raw Text],
    -- Human readable version of the fix:
    '|a' + missing_code.collection AS [Readable New Value],
    -- The actual string including MARC control characters:
    CHAR(31) + 'a' + missing_code.collection + CHAR(30) AS [New Raw Text]
FROM bib b
INNER JOIN (
    -- Isolate Bibs with exactly 2 identical 049 tags
    SELECT bib#, MAX(tagord) as duplicate_tagord
    FROM bib
    WHERE tag = '049'
    GROUP BY bib#
    HAVING COUNT(*) = 2 AND MIN(text) = MAX(text)
) as duplicates 
    ON b.bib# = duplicates.bib# 
    AND b.tagord = duplicates.duplicate_tagord
INNER JOIN (
    -- Find the collection code present on an item but missing from the 049 tags
    SELECT DISTINCT i.bib#, i.collection
    FROM item i
    WHERE NOT EXISTS (
        SELECT 1 FROM bib b2 
        WHERE b2.bib# = i.bib# AND b2.tag = '049' 
        AND b2.text LIKE '%' + i.collection + '%'
    )
) as missing_code 
    ON b.bib# = missing_code.bib#
WHERE b.tag = '049'
ORDER BY b.bib#;
