-- 1a. Find the install/upgrade clusters
-- READ-ONLY
--
-- GENERATED from db-scratch-table-cleanup/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Large counts on one timestamp = a vendor install or upgrade event.
-- Isolated singles = created by hand.
-- max_created is the value to paste into @VendorCutoff below: the last moment
-- of the cluster, at the second precision the later steps compare on.
SELECT
    CONVERT(char(16), t.create_date, 120)      AS [cluster],
    COUNT(*)                                   AS [tables_created],
    CONVERT(char(19), MAX(t.create_date), 120) AS [max_created]
FROM sys.tables t
WHERE t.is_ms_shipped = 0
GROUP BY CONVERT(char(16), t.create_date, 120)
ORDER BY [cluster];
