-- 1b. Candidates, with the evidence for judging them
-- READ-ONLY
--
-- GENERATED from db-scratch-table-cleanup/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

DECLARE @VendorCutoff datetime = '2099-01-01 00:00:00';   -- from 1a

SELECT
    t.name                                   AS [table_name],
    CONVERT(char(19), t.create_date, 120)    AS [created],
    CONVERT(char(19), t.modify_date, 120)    AS [last_modified],
    ISNULL(SUM(p.rows), 0)                   AS [rows],
    (SELECT COUNT(*) FROM sys.columns c
      WHERE c.object_id = t.object_id)       AS [columns],
    -- Vendor tables are built from Horizon's user-defined types. A scratch
    -- copy made by SELECT INTO inherits base types instead.
    (SELECT COUNT(*) FROM sys.columns c
     INNER JOIN sys.types ty ON ty.user_type_id = c.user_type_id
      WHERE c.object_id = t.object_id AND ty.is_user_defined = 1) AS [udt_cols],
    CASE WHEN EXISTS (SELECT 1 FROM sys.indexes i
                      WHERE i.object_id = t.object_id AND i.is_primary_key = 1)
         THEN 'YES' ELSE '' END              AS [declared_pk],
    CASE WHEN EXISTS (SELECT 1 FROM sys.indexes i
                      WHERE i.object_id = t.object_id AND i.is_unique = 1)
         THEN 'yes' ELSE '' END              AS [unique_idx]
FROM sys.tables t
LEFT JOIN sys.partitions p
       ON p.object_id = t.object_id AND p.index_id IN (0,1)
WHERE t.is_ms_shipped = 0
  AND t.create_date > @VendorCutoff
GROUP BY t.name, t.object_id, t.create_date, t.modify_date
ORDER BY [udt_cols] DESC, [columns] DESC, t.name;
