-- 1c. Does anything depend on them?
-- READ-ONLY
--
-- GENERATED from db-scratch-table-cleanup/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

DECLARE @VendorCutoff datetime = '2099-01-01 00:00:00';   -- from 1a

-- Views / procedures / functions referencing a candidate
SELECT
    OBJECT_NAME(d.referencing_id) AS [referenced_by],
    o.type_desc                   AS [referencer_type],
    d.referenced_entity_name      AS [candidate_table]
FROM sys.sql_expression_dependencies d
INNER JOIN sys.objects o ON o.object_id = d.referencing_id
INNER JOIN sys.tables  t ON t.name = d.referenced_entity_name
WHERE t.is_ms_shipped = 0
  AND t.create_date > @VendorCutoff
ORDER BY d.referenced_entity_name, [referenced_by];

-- Foreign keys pointing AT a candidate (these would block the DROP anyway)
SELECT
    fk.name                          AS [fk_name],
    OBJECT_NAME(fk.parent_object_id) AS [child_table],
    t.name                           AS [candidate_table]
FROM sys.foreign_keys fk
INNER JOIN sys.tables t ON t.object_id = fk.referenced_object_id
WHERE t.is_ms_shipped = 0
  AND t.create_date > @VendorCutoff
ORDER BY t.name;
