-- 1d. Generate the DROP script for review
-- WRITES - review before running
--
-- GENERATED from db-scratch-table-cleanup/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

DECLARE @VendorCutoff datetime = '2099-01-01 00:00:00';   -- from 1a

-- Tables to keep despite matching the predicate. Reason travels with the name.
DECLARE @Keep TABLE (name sysname PRIMARY KEY, reason nvarchar(200));
INSERT INTO @Keep VALUES
 ('item_circ_renewal', 'Horizon: circ renewal history, declared PK, 15 UDT cols'),
 ('bstat_group',       'Horizon: lookup, one of 19 sibling *_group tables'),
 ('sort_order',        'Horizon: character-equivalence data for browse indexes');

SELECT
    'IF OBJECT_ID(''dbo.' + t.name + ''',''U'') IS NOT NULL' +
    ' BEGIN DROP TABLE dbo.[' + t.name + ']; PRINT ''dropped ' + t.name + '''; END' +
    ' ELSE PRINT ''' + t.name + ' not present'';'   AS [drop_statement],
    ISNULL(SUM(p.rows), 0)                          AS [rows_it_holds]
FROM sys.tables t
LEFT JOIN sys.partitions p
       ON p.object_id = t.object_id AND p.index_id IN (0,1)
WHERE t.is_ms_shipped = 0
  AND t.create_date > @VendorCutoff
  AND NOT EXISTS (SELECT 1 FROM sys.sql_expression_dependencies d
                  WHERE d.referenced_entity_name = t.name)
  AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys fk
                  WHERE fk.referenced_object_id = t.object_id)
  AND NOT EXISTS (SELECT 1 FROM @Keep k WHERE k.name = t.name)
GROUP BY t.name
ORDER BY t.name;
