-- 2a. Count-gated — when you approved the whole 1d list
-- WRITES - review before running
--
-- GENERATED from db-scratch-table-cleanup/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SET NOCOUNT ON;
SET LOCK_TIMEOUT 10000;      -- fail fast on a lock rather than hanging

DECLARE @VendorCutoff datetime = '2099-01-01 00:00:00';   -- same value as 1d
DECLARE @ExpectedCount int    = 0;                        -- rows 1d returned

DECLARE @Keep TABLE (name sysname PRIMARY KEY, reason nvarchar(200));
INSERT INTO @Keep VALUES
 ('item_circ_renewal', 'Horizon: circ renewal history, declared PK, 15 UDT cols'),
 ('bstat_group',       'Horizon: lookup, one of 19 sibling *_group tables'),
 ('sort_order',        'Horizon: character-equivalence data for browse indexes');

IF OBJECT_ID('tempdb..#drop_list') IS NOT NULL DROP TABLE #drop_list;

-- Character-identical to 1d's WHERE clause. If you change one, change both.
SELECT t.name
INTO #drop_list
FROM sys.tables t
WHERE t.is_ms_shipped = 0
  AND t.create_date > @VendorCutoff
  AND NOT EXISTS (SELECT 1 FROM sys.sql_expression_dependencies d
                  WHERE d.referenced_entity_name = t.name)
  AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys fk
                  WHERE fk.referenced_object_id = t.object_id)
  AND NOT EXISTS (SELECT 1 FROM @Keep k WHERE k.name = t.name);

DECLARE @actual int = (SELECT COUNT(*) FROM #drop_list);
PRINT 'candidates now: ' + CAST(@actual AS varchar(10))
    + '   approved: '    + CAST(@ExpectedCount AS varchar(10));

IF @actual <> @ExpectedCount
BEGIN
    RAISERROR('ABORTED: the candidate set changed since you reviewed it. Re-run the audit.', 16, 1);
    RETURN;
END

DECLARE @name sysname, @sql nvarchar(400), @ok int = 0, @failed int = 0;
DECLARE c CURSOR LOCAL FAST_FORWARD FOR SELECT name FROM #drop_list ORDER BY name;
OPEN c;
FETCH NEXT FROM c INTO @name;
WHILE @@FETCH_STATUS = 0
BEGIN
    -- QUOTENAME, not concatenation: the name comes from a catalog view, but
    -- building dynamic SQL from an unquoted identifier is never acceptable.
    SET @sql = N'DROP TABLE dbo.' + QUOTENAME(@name) + N';';
    BEGIN TRY
        EXEC sp_executesql @sql;
        SET @ok = @ok + 1;
        PRINT '  dropped  ' + @name;
    END TRY
    BEGIN CATCH
        -- Per-table, so one locked table does not abandon the rest.
        SET @failed = @failed + 1;
        PRINT '  FAILED   ' + @name + '  -> ' + ERROR_MESSAGE();
    END CATCH
    FETCH NEXT FROM c INTO @name;
END
CLOSE c;
DEALLOCATE c;

PRINT '';
PRINT 'dropped ' + CAST(@ok AS varchar(10))
    + ', failed ' + CAST(@failed AS varchar(10));

SET LOCK_TIMEOUT -1;   -- session-scoped; reset or later queries inherit 10s
