-- 2b. Explicit list — when you kept only some of the 1d output
-- WRITES - review before running
--
-- GENERATED from db-scratch-table-cleanup/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SET LOCK_TIMEOUT 10000;

-- <<< PASTE YOUR EDITED DROP STATEMENTS FROM 1d HERE >>>
-- IF OBJECT_ID('dbo.SomeScratchTable','U') IS NOT NULL
--   BEGIN DROP TABLE dbo.[SomeScratchTable]; PRINT 'dropped SomeScratchTable'; END
-- ELSE PRINT 'SomeScratchTable not present';

SET LOCK_TIMEOUT -1;
