-- The Report (Read-Only)
-- READ-ONLY
--
-- GENERATED from 590-ebk-purchase-dda-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT
    b.[bib#]      AS [bib#],
    ebk.processed AS [processed],
    b.text        AS [text],
    b.tag         AS [tag]
FROM bib b
INNER JOIN (
        SELECT DISTINCT [bib#], processed
        FROM item_with_title
        WHERE collection = 'EBK'
    ) ebk
    ON ebk.[bib#] = b.[bib#]
WHERE b.tag = '590'
  AND (b.text LIKE '%purchase%' OR b.text LIKE '%DDA%')
  AND EXISTS (                       -- bib has a 590 containing 'purchase'
        SELECT 1 FROM bib bp
        WHERE bp.[bib#] = b.[bib#]
          AND bp.tag = '590'
          AND bp.text LIKE '%purchase%'
      )
  AND EXISTS (                       -- bib has a 590 containing 'DDA'
        SELECT 1 FROM bib bd
        WHERE bd.[bib#] = b.[bib#]
          AND bd.tag = '590'
          AND bd.text LIKE '%DDA%'
      )
ORDER BY b.[bib#], b.tagord;
