<#
.SYNOPSIS
    Regenerates the generated pages under docs/schema/index/ from the raw CSV
    exports in "horizon-schema/".

.DESCRIPTION
    The CSVs in "horizon-schema/" are the source of truth; the pages this script
    writes are derived and must never be hand-edited. Re-run after refreshing the
    exports (e.g. following a Horizon upgrade).

    Only files under docs/schema/index/ are generated. Everything else in
    docs/schema/ is hand-written and is left untouched.

    The exports are saved from SSMS with *no header row*, so each CSV is read
    with an explicit -Header matching the column order of the export query in
    docs/schema/README.md. If you change an export query, change the header here
    to match.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File tools\Generate-SchemaDocs.ps1
#>

[CmdletBinding()]
param(
    [string] $RepoRoot
)

$ErrorActionPreference = 'Stop'

# $PSScriptRoot is not reliably populated while param() defaults are bound in
# Windows PowerShell 5.1, so resolve the repo root here instead.
if (-not $RepoRoot) {
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    $RepoRoot  = Split-Path -Parent $scriptDir
}

$RawDir = Join-Path $RepoRoot 'horizon-schema'
$OutDir = Join-Path $RepoRoot 'docs\schema\index'

if (-not (Test-Path $RawDir)) { throw "Raw export folder not found: $RawDir" }
if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Path $OutDir -Force | Out-Null }

# Column orders below MUST match the export queries in docs/schema/README.md.
$ColumnsHeader = @(
    'schema','object','object_type','ord','column','declared_type','base_type',
    'len_bytes','prec','scale','nullable','is_identity','is_computed',
    'collation','pk','pk_ord','default_definition'
)
$IndexHeader = @(
    'schema','object','index_name','index_type','is_pk','is_unique',
    'key_ord','column','direction','part'
)
$FkHeader = @(
    'fk_name','parent_schema','parent_table','parent_column',
    'referenced_schema','referenced_table','referenced_column',
    'col_ord','on_delete','on_update','disabled'
)

function Import-RawCsv {
    param([string] $Path, [string[]] $Header)
    if (-not (Test-Path $Path)) {
        Write-Warning "Missing export: $Path - dependent sections will be omitted."
        return @()
    }
    # SSMS writes a UTF-8 BOM; Import-Csv strips it from the first field itself.
    return Import-Csv -Path $Path -Header $Header
}

$colsPath = Join-Path $RawDir 'all_tables_all_views.csv'
$idxPath  = Join-Path $RawDir 'indexes_and_keys.csv'
$fkPath   = Join-Path $RawDir 'foreign_keys.csv'

$cols = Import-RawCsv -Path $colsPath -Header $ColumnsHeader
$idx  = Import-RawCsv -Path $idxPath  -Header $IndexHeader
$fks  = Import-RawCsv -Path $fkPath   -Header $FkHeader

if ($cols.Count -eq 0) { throw "No column data read from $colsPath" }

Write-Host "Read $($cols.Count) columns, $($idx.Count) index entries, $($fks.Count) FK columns."

# ---------------------------------------------------------------------------
# Grain: the unique index(es) on each object. In this database only 6 columns
# carry a declared PRIMARY KEY, so unique indexes are the real statement of a
# table's grain. See docs/schema/conventions.md.
# ---------------------------------------------------------------------------
$grain = @{}
$uniqueIdx = $idx | Where-Object { $_.is_unique -eq 'yes' -and $_.part -eq 'KEY' }
foreach ($g in ($uniqueIdx | Group-Object object, index_name)) {
    $rows = $g.Group | Sort-Object { [int] $_.key_ord }
    $obj  = $rows[0].object
    $cList = ($rows | ForEach-Object { $_.column }) -join ', '
    if (-not $grain.ContainsKey($obj)) { $grain[$obj] = New-Object System.Collections.ArrayList }
    [void] $grain[$obj].Add($cList)
}

# ---------------------------------------------------------------------------
# all-objects.md - one row per table/view: type, column count, proven grain.
# ---------------------------------------------------------------------------
$objGroups = $cols | Group-Object object
$sb = New-Object System.Text.StringBuilder

[void] $sb.AppendLine('# Object index (generated)')
[void] $sb.AppendLine()
[void] $sb.AppendLine('<!-- GENERATED by tools/Generate-SchemaDocs.ps1 - do not edit by hand. -->')
[void] $sb.AppendLine()
[void] $sb.AppendLine('Every table and view in the database, with its column count and its **grain**')
[void] $sb.AppendLine('(the column set a unique index proves is one row). Grain is what tells you')
[void] $sb.AppendLine('whether a join fans out - read it before writing one.')
[void] $sb.AppendLine()
[void] $sb.AppendLine('`(none)` means no unique index exists, so **any join to this object may')
[void] $sb.AppendLine('multiply rows**. Collapse it with `EXISTS`, `DISTINCT`, or aggregation.')
[void] $sb.AppendLine()
[void] $sb.AppendLine('This page is for orientation. For the columns of a specific object, grep the')
[void] $sb.AppendLine('CSV - see "Looking up a column" in [AGENTS.md](../AGENTS.md).')
[void] $sb.AppendLine()

$tableCount = ($cols | Where-Object { $_.object_type -eq 'TABLE' } | Select-Object -ExpandProperty object -Unique).Count
$viewCount  = ($cols | Where-Object { $_.object_type -eq 'VIEW'  } | Select-Object -ExpandProperty object -Unique).Count
[void] $sb.AppendLine("**$($objGroups.Count) objects** - $tableCount tables, $viewCount views, $($cols.Count) columns total.")
[void] $sb.AppendLine()
[void] $sb.AppendLine('| Object | Type | Cols | Grain (unique index) |')
[void] $sb.AppendLine('| --- | --- | ---: | --- |')

foreach ($g in ($objGroups | Sort-Object Name)) {
    $name = $g.Name
    $type = $g.Group[0].object_type
    $n    = $g.Count
    if ($grain.ContainsKey($name)) {
        $gr = ($grain[$name] | ForEach-Object { '`' + $_ + '`' }) -join ' / '
    } else {
        $gr = '(none)'
    }
    [void] $sb.AppendLine("| ``$name`` | $type | $n | $gr |")
}

$allObjPath = Join-Path $OutDir 'all-objects.md'
$sb.ToString() | Out-File -FilePath $allObjPath -Encoding utf8
Write-Host "Wrote $allObjPath"

# ---------------------------------------------------------------------------
# joins.md - declared foreign keys, the verified relationship map.
# ---------------------------------------------------------------------------
$sb = New-Object System.Text.StringBuilder
[void] $sb.AppendLine('# Verified join map (generated)')
[void] $sb.AppendLine()
[void] $sb.AppendLine('<!-- GENERATED by tools/Generate-SchemaDocs.ps1 - do not edit by hand. -->')
[void] $sb.AppendLine()
[void] $sb.AppendLine('Every **declared** foreign key: a relationship the database itself enforces.')
[void] $sb.AppendLine()
[void] $sb.AppendLine('> **Absence here does not mean two tables are unrelated.** Horizon leaves most')
[void] $sb.AppendLine('> of its relationships undeclared - `bib` to `item` is the obvious example, and')
[void] $sb.AppendLine('> it has no FK. This is the list of enforced constraints, not a data model.')
[void] $sb.AppendLine('> For an undeclared join, confirm the grain of both sides in')
[void] $sb.AppendLine('> [all-objects.md](all-objects.md) before assuming it will not fan out.')
[void] $sb.AppendLine()

if ($fks.Count -gt 0) {
    $fkGroups = $fks | Group-Object fk_name
    [void] $sb.AppendLine("**$($fkGroups.Count) foreign keys.**")
    [void] $sb.AppendLine()
    [void] $sb.AppendLine('| Child table | Child column(s) | References | Referenced column(s) | On delete |')
    [void] $sb.AppendLine('| --- | --- | --- | --- | --- |')
    foreach ($g in ($fkGroups | Sort-Object { $_.Group[0].parent_table }, Name)) {
        $rows = $g.Group | Sort-Object { [int] $_.col_ord }
        $pt = $rows[0].parent_table
        $rt = $rows[0].referenced_table
        $pc = ($rows | ForEach-Object { $_.parent_column }) -join ', '
        $rc = ($rows | ForEach-Object { $_.referenced_column }) -join ', '
        $od = $rows[0].on_delete
        if ($rows[0].disabled -eq 'DISABLED') { $od = "$od **(DISABLED)**" }
        [void] $sb.AppendLine("| ``$pt`` | ``$pc`` | ``$rt`` | ``$rc`` | $od |")
    }
} else {
    [void] $sb.AppendLine('_No foreign key export found._')
}

$joinPath = Join-Path $OutDir 'joins.md'
$sb.ToString() | Out-File -FilePath $joinPath -Encoding utf8
Write-Host "Wrote $joinPath"

# ---------------------------------------------------------------------------
# no-unique-index.md - the fan-out hazard list.
# ---------------------------------------------------------------------------
$noGrain = $objGroups | Where-Object { -not $grain.ContainsKey($_.Name) } | Sort-Object Name
$sb = New-Object System.Text.StringBuilder
[void] $sb.AppendLine('# Objects with no unique index (generated)')
[void] $sb.AppendLine()
[void] $sb.AppendLine('<!-- GENERATED by tools/Generate-SchemaDocs.ps1 - do not edit by hand. -->')
[void] $sb.AppendLine()
[void] $sb.AppendLine('These objects have **no unique index**, so nothing constrains them to one row')
[void] $sb.AppendLine('per key. Joining to one can multiply your result set without warning - the')
[void] $sb.AppendLine('Cartesian product hazard this repo exists to guard against.')
[void] $sb.AppendLine()
[void] $sb.AppendLine('Views appear here routinely (a view inherits no index of its own); that is')
[void] $sb.AppendLine('expected and does not by itself mean the view is not one row per key.')
[void] $sb.AppendLine('Determine a view''s grain from its underlying tables.')
[void] $sb.AppendLine()
[void] $sb.AppendLine("**$($noGrain.Count) objects.**")
[void] $sb.AppendLine()
[void] $sb.AppendLine('| Object | Type | Cols |')
[void] $sb.AppendLine('| --- | --- | ---: |')
foreach ($g in $noGrain) {
    [void] $sb.AppendLine("| ``$($g.Name)`` | $($g.Group[0].object_type) | $($g.Count) |")
}

$noIdxPath = Join-Path $OutDir 'no-unique-index.md'
$sb.ToString() | Out-File -FilePath $noIdxPath -Encoding utf8
Write-Host "Wrote $noIdxPath"

# ---------------------------------------------------------------------------
# date-columns.md - every smallint date column, the most pervasive convention.
# ---------------------------------------------------------------------------
$dateCols = $cols | Where-Object {
    $_.base_type -eq 'smallint' -and ($_.column -match 'date$' -or $_.column -match '_date')
} | Sort-Object object, column

$sb = New-Object System.Text.StringBuilder
[void] $sb.AppendLine('# Horizon integer date columns (generated)')
[void] $sb.AppendLine()
[void] $sb.AppendLine('<!-- GENERATED by tools/Generate-SchemaDocs.ps1 - do not edit by hand. -->')
[void] $sb.AppendLine()
[void] $sb.AppendLine('Every `smallint` column whose name marks it as a date. These do **not** hold')
[void] $sb.AppendLine('a SQL `date`; they hold a day count. See "Dates" in')
[void] $sb.AppendLine('[conventions.md](../conventions.md) for how to filter one correctly.')
[void] $sb.AppendLine()
[void] $sb.AppendLine("**$($dateCols.Count) columns across $(($dateCols | Select-Object -ExpandProperty object -Unique).Count) objects.**")
[void] $sb.AppendLine()
[void] $sb.AppendLine('| Object | Column | Paired time column |')
[void] $sb.AppendLine('| --- | --- | --- |')
# One pass to index every object|column, then O(1) lookups. Scanning $cols
# (14,103 rows) once per date column (952) was up to 13M comparisons and was
# the dominant cost of this script.
$colKeys = New-Object 'System.Collections.Generic.HashSet[string]'
foreach ($c in $cols) { [void] $colKeys.Add($c.object + '|' + $c.column) }

foreach ($d in $dateCols) {
    # -replace only rewrites a trailing 'date', so a column matched by the
    # '_date' branch (e.g. run_date_int) comes back unchanged and would report
    # itself as its own paired time column. Require a real rename.
    $timeName = $d.column -replace 'date$', 'time'
    if ($timeName -ne $d.column -and $colKeys.Contains($d.object + '|' + $timeName)) {
        $t = "``$timeName``"
    } else { $t = '-' }
    [void] $sb.AppendLine("| ``$($d.object)`` | ``$($d.column)`` | $t |")
}

$datePath = Join-Path $OutDir 'date-columns.md'
$sb.ToString() | Out-File -FilePath $datePath -Encoding utf8
Write-Host "Wrote $datePath"

Write-Host ''
Write-Host 'Done. Generated pages are under docs/schema/index/.'
Write-Host 'Hand-written pages in docs/schema/ were not touched.'
